class Const:
    SCREEN_WIDTH = 800
    SCREEN_HEIGHT = 600
    BG_COLOR = (0, 0, 0)

    SPACESHIP_ACCELERATION = 0.5
    SPACESHIP_MAX_SPEED = 20
    SPACESHIP_FLAME_OFFSET_X_LEFT = 22
    SPACESHIP_FLAME_OFFSET_X_RIGHT = 44
    SPACESHIP_FLAME_OFFSET_Y = 73
    SPACESHIP_ANIMATION_TO_SPEED_RATIO = 2
    SPACESHIP_SPEED_DROP_ON_SIDE_IMPACT = 1.5

    FRAME_TIME = 0.05

    MISSILE_INITIAL_SPEED = 0.1
    MISSILE_ACCELERATION = 0.3
    MISSILE_STOWED_OFFSET_X_LEFT = 18
    MISSILE_STOWED_OFFSET_X_RIGHT = 48
    MISSILE_STOWED_OFFSET_Y = 27

    STAR_NUM_SMALL = 60
    STAR_NUM_BRIGHT = 20
    STAR_SPEED_SMALL = (0.1, 0.2)
    STAR_SPEED_BRIGHT = (0.2, 0.3)
    STAR_COORD_APPEAR = -5
    STAR_ANIMATION_CHANCE = 30  # The larger the number here - the smaller the chance is

    INITIAL_X_POS = SCREEN_WIDTH / 2
    INITIAL_Y_POS = SCREEN_HEIGHT - SCREEN_HEIGHT / 10
